### ISSUE TITLE
Uneccessary files

### ISSUE THREAD

**Issue by NyakudyaA** [uilic/SplitPolygon#1]
@uilic Please remove .pyc files they are automatically created on install

**Comment by uilic** [comment]
Done. Thanks.

**Comment by uilic** [comment]
I also saw that I missed the ui file I don't know why it hadn't been there, but I added it.

**Comment by NyakudyaA** [comment]
Ok will test and approve after if they are no issues

**Comment by NyakudyaA** [comment]
@uilic was trying to split a polygon by percentage and put 25 and got the following error. Please make sure errors are handled properly.
![error](https://user-images.githubusercontent.com/2510900/35441856-d602f7b8-02ad-11e8-86a3-58079806742e.png)

**Comment by uilic** [comment]
Problem is with the angle, not with percentage, which angle did you enter? You should fill the angle part propertly.

**Comment by uilic** [comment]
@NyakudyaA Problem is with the angle, not with percentage, which angle did you enter? You should fill the angle part.

**Comment by uilic** [comment]
@NyakudyaA I will make some default values on start, and make it a little bit more intuitive later today.

**Comment by pcav** [comment]
Please confirm when complete.
Thanks.

**Comment by uilic** [comment]
@pcav The changes have been made a few days ago, you just only shouldn't enter values at the area and width part that are bigger than polygons area and width itself, which is logical. And let me repeat, it would not work for concave polygons.
