### ISSUE TITLE
Data Entry

### ISSUE THREAD

**Issue by AbundantGIS** [uilic/SplitPolygon#2]
I downloaded the plugin and was able to load in the dataset that I want split, but it won't let me adjust any of the parameters except for the angle and percentage of polygon. I think its only let me enter in parameters with adjustment arrows. 

Any help would be greatly appreciated. 

Thanks.

**Comment by uilic** [comment]
@AbundantGIS I downloaded it and tested  once again everything works properly. Check if your polygon is convex, it doesn't work for concave polygons. Then, check if your cutting area is not bigger than the area of polygon itself, also check if the width that you need to enter is not bigger than polygon width. You can see in the pictures below that everything it is working fine.
![screenshot from 2018-02-10 15-49-07](https://user-images.githubusercontent.com/32105551/36063227-64f14d8a-0e7a-11e8-8155-6b4600b9912d.png)
![screenshot from 2018-02-10 15-49-48](https://user-images.githubusercontent.com/32105551/36063228-65187e0a-0e7a-11e8-8860-b93b7093652d.png)
![screenshot from 2018-02-10 15-49-52](https://user-images.githubusercontent.com/32105551/36063229-653e4306-0e7a-11e8-8739-8992d1f8093d.png)
![screenshot from 2018-02-10 15-50-53](https://user-images.githubusercontent.com/32105551/36063230-656e0532-0e7a-11e8-8953-fd31f4127c2e.png)
![screenshot from 2018-02-10 15-51-01](https://user-images.githubusercontent.com/32105551/36063231-65c607be-0e7a-11e8-9d19-c781021a6955.png)
![screenshot from 2018-02-10 15-51-23](https://user-images.githubusercontent.com/32105551/36063233-6639ddd8-0e7a-11e8-8107-fd54aa00ee17.png)
![screenshot from 2018-02-10 15-51-27](https://user-images.githubusercontent.com/32105551/36063234-66ab4b08-0e7a-11e8-85bd-3e36ebb2c2e4.png)
![screenshot from 2018-02-10 15-51-55](https://user-images.githubusercontent.com/32105551/36063235-672420b4-0e7a-11e8-88dc-fe5ba1855fbd.png)
![screenshot from 2018-02-10 15-52-00](https://user-images.githubusercontent.com/32105551/36063236-67a06836-0e7a-11e8-9b87-232fcb98cdca.png)

**Comment by AbundantGIS** [comment]
Thanks, for the advice. Unfortunately, my dataset has concave polygons. Appreciate your assistance on this!
